### PR TITLE
refactor: optimized nftValidation function by using Alchemy-sdk

### PR DESCRIPTION
**Pull request by pokhrelanmol**

### CODE REVIEW

**Comment by 0xinit** [comment]
@pokhrelanmol do you wanna change the frontend spelling mistake from "Yout" to "Your" before i merge it? Everything else looks fine.

**Comment by pokhrelanmol** [comment]
Hey, I fixed a typo with some minor changes. Please have a look.

**Comment by pokhrelanmol** [comment]
You can always visit  [THIS LINK](https://alchemy-goerli-eth-faucet-frontend-next.vercel.app/)  to see the output.

**Comment by 0xinit** [comment]
Nice work! Merged.

Another change might be to add "Donate X amount" rather than 0.1

If I want to donate 10geth, I dont have option to fund it, so it's a good idea to have a dialog box that let's me select the amount of geth im sending.

**Comment by 0xinit** [comment]
actually, there are merge issues, can you resolve that as well? @pokhrelanmol

**Comment by pokhrelanmol** [comment]
can you have a look now? I guess the conflict is now resolved.

**Comment by pokhrelanmol** [comment]
> Nice work!
> 
> Another change might be to add "Donate X amount" rather than 0.1
> 
> If I want to donate 10geth, I dont have option to fund it, so it's a good idea to have a dialog box that let's me select the amount of geth im sending.

Ya that's a feature I'm also planning to write. Will push the code for it soon...

**Comment by 0xinit** [comment]
great work! @pokhrelanmol

**Pull request merged**
